name: Docker Image Test Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check for relevant file changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          imagestuff:
            - '.dockerignore'
            - 'ansible.cfg'
            - 'Dockerfile'

    - name: Build the Docker image
      if: steps.filter.outputs.imagestuff == 'true'
      run: docker build . --file Dockerfile --tag ansible-docker:$(date +%s)
